### ISSUE TITLE
Question about the meaning of D_norm_factors

### ISSUE THREAD

**Issue by zhang-bin1999** [MNagtegaal/SPIJN#1]
Hi, thank you so much for your contributions and I was wondering what's the meaning of D_norm_factors? Is it a two-paradigm number taken from each row of the dictionary matrix? Or how could I calculate it if I have the dictionary and compressed matrix? Thank you a lot!

**Comment by MNagtegaal** [comment]
Hi! 
D_norm_factors are the normalization factors you used to normalize the dictionary. 
From the paper: 
> Both the measured signals X and the dictionary D are normalized such that $\left\lVert d_i\right\rVert_2=\left\lVert x_j\right\rVert_2=1, \forall i,j$. The normalization of the dictionary prevents a bias caused by high signal intensity, the normalization of the signals makes sure that all voxels have an equal influence on the joint sparsity. 

I added #2 to clarify this
